feat(#261): add new folder with deployment commands and delete deploy…
dojoengine/book pull request #271
Opened 2024-05-13 05:34 UTC by juandiegocv27

This is the issue #261.

Just modified and add some features for Slot CLI documentation that will bring great context with:

-deleted deployments page.
-added create, delete, update, describe, list, logs and help command pages.

![image](https://github.com/dojoengine/book/assets/101369290/53a941fc-06d6-4c6a-b9ed-cf48526f90a7)

@kariy.

2024-05-13 05:50 UTC, juandiegocv27 commented
Hi, @kariy I have an error, in this part, could you check it, I'll fix it as soon as possible

2024-05-13 13:12 UTC, kariy reviewed
hey @juandiegocv27 thanks for the work!

can you also update the sidebar [config](https://github.com/dojoengine/book/blob/76bc33372761cd40d4121b7facd6c1373b3d93f0/vocs.config.ts#L188) so that the new pages would be accessible from the sidebar ?

<img width="307" alt="Screenshot 2024-05-13 at 9 12 24 AM" src="https://github.com/dojoengine/book/assets/26515232/92d09962-ef90-449a-aaca-1009d2259118">

2024-05-13 15:03 UTC, juandiegocv27 commented
> hey @juandiegocv27 thanks for the work!
> 
> 
> 
> can you also update the sidebar [config](https://github.com/dojoengine/book/blob/76bc33372761cd40d4121b7facd6c1373b3d93f0/vocs.config.ts#L188) so that the new pages would be accessible from the sidebar ?
> 
> 
> 
> <img width="307" alt="Screenshot 2024-05-13 at 9 12 24 AM" src="https://github.com/dojoengine/book/assets/26515232/92d09962-ef90-449a-aaca-1009d2259118">
> 
> 

Ok sure 🫡

2024-05-13 20:51 UTC, juandiegocv27 commented
Hi @kariy, I just fix it, and agreggate some features, hope for feedback

2024-05-28 01:43 UTC, juandiegocv27 commented
HI @kariy @milancermak @milancermak, is this PR is still relevant? Please let me know if there's anything else you’d like me to add or if you have any feedback. I'm happy to make any changes you need. Thanks

2024-05-28 05:14 UTC, ponderingdemocritus commented
@juandiegocv27 could you fix the conflict

2024-05-28 05:17 UTC, juandiegocv27 commented
@ponderingdemocritus sure, but, talking in discord with @kariy told me to erase the file deployments.md, so I could return it, but all that I do was put more stuff and make deployments a folder

2024-05-28 06:31 UTC, juandiegocv27 commented
@ponderingdemocritus @kariy just fix the conflict

2024-05-28 07:10 UTC, juandiegocv27 commented
@ponderingdemocritus @kariy just fix the conflict, but new conflict appear, now the conflict dont tell me what to fix

2024-05-29 04:47 UTC, juandiegocv27 commented
@ponderingdemocritus @kariy @milancermak @ptisserand, just resolved conflicts

2024-05-31 14:09 UTC, kariy requested changes

2024-06-04 07:05 UTC, juandiegocv27 commented
@ponderingdemocritus @kariy @milancermak @ptisserand Fix all the code and ready to merge: 
![image](https://github.com/dojoengine/book/assets/101369290/b7952c42-7607-4c01-8339-cc4b576f27d1)

waiting for more feedback 😎🚀

2024-06-08 05:41 UTC, juandiegocv27 commented on docs/pages/toolchain/slot/Deployments/delete.md
> +```
this is ready

2024-06-08 05:42 UTC, juandiegocv27 commented on docs/pages/toolchain/slot/Deployments/describe.md
> +        - **`-index-pending <boolean>`**: Enable or disable indexing of pending transactions.
already

2024-06-08 05:42 UTC, juandiegocv27 commented on docs/pages/toolchain/slot/Deployments/help.md
ok

2024-06-08 05:43 UTC, juandiegocv27 commented on docs/pages/toolchain/slot/Deployments/delete.md
> +This command is crucial for managing the lifecycle of services by allowing users to terminate and clean up deployments when they are no longer needed or require replacement.
I just put it some kind like that, tell me what you about it

2024-06-08 15:01 UTC, glihm requested changes
Thanks for the work here @juandiegocv27!

Some important points:
1. consistency: `slot` should be formatted with consistency as sometimes you use `Slot` and sometimes Slot.
2. formatting: I've left some commands on formatting, not on all the lines that require changes, you may do a general review of formatting.

2024-06-11 18:46 UTC, juandiegocv27 commented
> Thanks for the work here @juandiegocv27!
> 
> 
> 
> Some important points:
> 
> 1. consistency: `slot` should be formatted with consistency as sometimes you use `Slot` and sometimes Slot.
> 
> 2. formatting: I've left some commands on formatting, not on all the lines that require changes, you may do a general review of formatting.

@glihm thanks a lot for the feedback, I'll work on it as fast as possible ⚡️

2024-07-14 14:09 UTC, juandiegocv27 commented on docs/pages/toolchain/slot/index.md
> +Slot is a robust toolchain designed by [Cartrige.gg](https://github.com/cartridge-gg/slot) for rapidly spinning up Katana and Torii instances. which are essential for testing and development in gamin
thanks for the feedback, already making changes

2024-07-16 20:10 UTC, juandiegocv27 commented
hI @glihm, @kariy, fix somethings in this issue, ready to merge🚀

2024-07-18 17:09 UTC, glihm reviewed
@juandiegocv27 thanks for the work here! Some comments that also apply to all commands.

Once done, this should be ready for merging!
Thank you for the iterations, let's know if you have any question!

2024-07-18 17:09 UTC, glihm commented on docs/pages/toolchain/slot/deployment-commands/create.md
> +    slot deployments create 'MyProject' katana --version "1.0" --block-time 10
We can remove the '' if the project has not spaces in it.
Same for the version. We can also update for a more recent version that exists:
```
slot d create example_project katana --version 1.0.0-alpha.1
```

2024-07-18 17:09 UTC, glihm commented on docs/pages/toolchain/slot/deployment-commands/create.md
> +    slot deployments create 'MyProject' torii --world 0x3fa481f41522b90b3684ecfab7650c259a76387fab9c380b7a959e3d4ac69f
Same here to be consistent, without the ''.

2024-07-18 17:09 UTC, glihm commented on vocs.config.ts
> +		              text: "deployments",
```suggestion
		              text: "Deployments",
```

2024-07-18 17:09 UTC, glihm commented on docs/pages/toolchain/slot/deployment-commands/delete.md
> +s
```suggestion

```

2024-07-18 17:09 UTC, glihm commented on docs/pages/toolchain/slot/deployment-commands/delete.md
> +    slot deployments delete 'MyProject' Katana
Same here let's show and example with snake case without `''`.

2024-07-18 17:09 UTC, glihm commented on docs/pages/toolchain/slot/deployment-commands/update.md
> +    slot deployments update 'MyProject' Katana --version "1.2" --block-time 12
Same comment for `''` and version. 👍

2024-07-18 17:09 UTC, glihm commented on docs/pages/toolchain/slot/deployment-commands/describe.md
> +    slot deployments describe 'MyProject' Katana --version "1.2"
Same comment for syntax, and we may actually add an output to show what's expected.

2024-07-18 17:09 UTC, glihm commented on docs/pages/toolchain/slot/deployment-commands/logs.md
> +### Response and Output
Those sections with response and output are great. Could we generalize it to the other commands showing real output + comments on it when required?

2024-07-18 17:09 UTC, glihm commented on docs/pages/toolchain/slot/deployment-commands/logs.md
> +### Usage
Comment that applies for all, let's use `##` here as the first level if `#`.

Like so, if we want to insert a new subsection, we can use `###`.

2024-07-18 17:12 UTC, juandiegocv27 commented
> @juandiegocv27 thanks for the work here! Some comments that also apply to all commands.
> 
> Once done, this should be ready for merging! Thank you for the iterations, let's know if you have any question!

Thank you for the feedback @glihm, I´ll make the changes as fast as possible

2024-07-18 21:45 UTC, glihm commented
> > @juandiegocv27 thanks for the work here! Some comments that also apply to all commands.
> > Once done, this should be ready for merging! Thank you for the iterations, let's know if you have any question!
> 
> Thank you for the feedback @glihm, I´ll make the changes as fast as possible

No rush, thank you for your contribution. 👍

2024-07-19 00:07 UTC, juandiegocv27 commented
> > > @juandiegocv27 thanks for the work here! Some comments that also apply to all commands.
> > > Once done, this should be ready for merging! Thank you for the iterations, let's know if you have any question!
> > 
> > 
> > Thank you for the feedback @glihm, I´ll make the changes as fast as possible
> 
> No rush, thank you for your contribution. 👍

Already fix and put response and output in every command😎 @glihm

2024-07-23 14:43 UTC, kariy approved these changes
lgtm

2024-07-23 14:46 UTC, merged

2024-07-24 17:02 UTC, juandiegocv27 commented
> lgtm

thank you so much