docs: add a testing cheat code file
dojoengine/book pull request #302
Opened 2024-06-25 09:27 UTC by od-hunter

Resolves https://github.com/dojoengine/book/issues/300

2024-06-26 17:40 UTC, glihm requested changes
Thanks for the work here.

Could you please add more realistic examples that actually work, using the correct `use` and instructions to actually access those functions from the corelib?

No problem at all with AI generated content, please make sure it's actually accurate.

Please don't hesitate if you have any question.

2024-07-01 21:05 UTC, glihm requested changes
> Could you please add more realistic examples that actually work, using the correct use and instructions to actually access those functions from the corelib?

Thanks for the work here, your examples are still using invalid Cairo Code. Could you please set Cairo examples that can be compiled to ensure the user can correctly test it? Thanks!

2024-07-07 20:36 UTC, od-hunter commented
@glihm please review, I’ve made necessary corrections

2024-07-08 20:39 UTC, glihm reviewed
> @glihm please review, I’ve made necessary corrections


Hum, I don't think you have the will to learn here, mostly copy-pasting wrong part of the code and some AI text and no actual understanding of the code.

Here's an other link to help you going through the implementation again: https://github.com/starkware-libs/cairo/blob/72d1d2f50e8c2c13d5414cc4365683299d8f3c8b/crates/cairo-lang-starknet/cairo_level_tests/l2_to_l1_messages.cairo#L69.

Would appreciate if the next iteration actually contain some changes that are relevant for the reader of the book. Otherwise, I'll close and un-assigned.

2024-07-09 11:39 UTC, od-hunter commented
Sir please I need your telegram I have questions to ask you

2024-07-09 14:57 UTC, glihm commented
> Sir please I need your telegram I have questions to ask you

No problem at all, you can come in Dojo discord any time, happy to answer any question. 🫡

2024-07-11 02:43 UTC, glihm requested changes
Thanks for the work done here @od-hunter.

I've corrected the two first, to give you some examples of working cairo.

Could you please review all the others to ensure they are compilable and working?

I suggest you to do the following to test them:

1. `scarb new my_proj` to create a new project.
2. Set the `Scarb.toml` to build starknet contract, [full example available here](https://github.com/software-mansion/scarb/tree/main/examples/starknet_hello_world).
3. Write one function for each cheat code with the same style I've given in this review. We prefer using assert instead of comments.
4. Finally, run `scarb test` to verify all your tests are green, and then you can just copy paste the code in each cheat code.

Thank you!

2024-07-11 02:43 UTC, glihm commented on pnpm-lock.yaml
Could you revert this file please?

2024-07-11 02:43 UTC, glihm commented on package-lock.json
This file should be reverted too. No changes expected. 👍

2024-07-11 02:43 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +- Simulating a fork or replay attack to test a contract's resilience.
```suggestion
```

2024-07-11 02:43 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +- Testing a contract's behavior at a specific block height, such as checking if a certain function is only callable after a certain block number.
```suggestion
This one is helpful to test a contract's behavior at a specific block height, such as checking if a certain function is only callable after a certain block number.
```

2024-07-11 02:43 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +get_block_nunmber(); // returns 1234567
```suggestion
assert!(get_block_number() == 1234567, 'bad block number');
```

2024-07-11 02:43 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +This cheat code helps you set the contract address to the provided value, allowing you to test contract deployment and interactions. You can apply this code when:
```suggestion
This cheat code helps you set the contract address to the provided value, allowing you to test contract deployment and interactions.
```

2024-07-11 02:43 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +- Testing a contract's behavior when deployed to a different address.
```suggestion
It is important to note that any test function is considered a contract, which by default uses the `0` address. Using `set_contract_address` allows you to mock the current address of the testing function, making it useful to call other contract that may use `get_caller_address`.
```

2024-07-11 02:43 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +use core::traits::{TryInto, Into};
```suggestion
```
Shouldn't be necessary.

2024-07-11 02:43 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +
```suggestion
use starknet::{testing, get_caller_address, contract_address_const};

let user_one = contract_address_const::<'user1'>();
testing::set_caller_address(user_one);
assert(get_caller_address() == user_one, 'bad caller';
```

2024-07-11 11:14 UTC, closed without merging