chore: cheat code documentation
dojoengine/book pull request #308
Opened 2024-07-11 11:12 UTC by od-hunter

resolves #300

2024-07-12 18:35 UTC, glihm requested changes
Thanks for the revision @od-hunter. Most of the examples are still not using real functions from the core lib. I've made some corrections but not all, could you please take the time to check if all the examples compile and make the according corrections with the examples given?

Like so, the reader of the book will have accurate information. 🫡

2024-07-12 18:35 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +- Simulating a scenario where a contract is upgraded to a different version.
this cheat code is about the version of the transaction, not the contract's version.
Could you please rephrase accordingly?

2024-07-12 18:35 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +use starknet::{testing, get_version};
```suggestion
use starknet::{testing, get_tx_info};
```
`get_version` function doesn't exist. It's the version of the transaction inside the transaction execution info:
```rust
testing::set_version(1);
assert_eq!(get_tx_info().unbox().version, 1_felt252);
```

2024-07-12 18:35 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +- Testing a contract's interaction with a specific account contract, such as a wallet contract.
```suggestion
- Testing a contract's interaction with a specific account contract.
```

2024-07-12 18:35 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +const contract: ContractAddress = contract_address_const::<'contract'>();
```suggestion
const contract = contract_address_const::<'contract'>();
```
Type is inferred, it makes the code more readable. 👍

2024-07-12 18:35 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +use starknet::{testing, get_account_contract_address, contract_address_const};
```suggestion
use starknet::{testing, get_tx_info, contract_address_const};
```
Same here, this function doesn't exist.

2024-07-12 18:35 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +assert(get_account_contract_address() == contract, 'wrong contract address');
```suggestion
assert_eq!(get_tx_info().unbox().account_contract_address.into(), contract);
```
Using `assert_eq!` you don't always require to put a reason. Can be sometimes shorter and better. :)

2024-07-31 23:41 UTC, glihm requested changes
@od-hunter thanks for the work here, in a good direction but not yet ready to be published.

I've prepared for you a test module that you can run to test all the cheat codes and adjust the documentation accordingly. Some of the examples are not working, could you please adjust with the given test module to ensure everything compiles? Thank you very much!

```rust
#[cfg(test)]
mod tests {
    use starknet::{testing, get_block_number, get_caller_address, get_contract_address, contract_address_const, get_block_timestamp, get_tx_info};

    #[test]
    fn f1() {
        testing::set_block_number(1234567);
        assert!(get_block_number() == 1234567, "bad block number");
    }

    #[test]
    fn f2() {
        let user_one = contract_address_const::<'user1'>();
        testing::set_caller_address(user_one);
        assert!(get_caller_address() == user_one, "bad caller");
    }

    #[test]
    fn f3() {
        let hub_address = contract_address_const::<'hub'>();
        testing::set_contract_address(hub_address);
        assert!(get_contract_address() == hub_address, "bad address");
    }

    #[test]
    fn f4() {
        testing::set_block_timestamp(123456);
        assert!(get_block_timestamp() == 123456, "bad timestamp");
    }

    #[test]
    fn f5() {
        testing::set_version('0.1.0');
        assert_eq!(get_tx_info().unbox().version, '0.1.0');
    }

    #[test]
    fn f6() {
        let contract = contract_address_const::<'contract'>(); 
        testing::set_account_contract_address(contract);
        assert_eq!(get_tx_info().unbox().account_contract_address.into(), contract);
    }

    #[test]
    fn f7() {
        testing::set_max_fee(123456);
        assert_eq!(get_tx_info().unbox().max_fee.into(), 123456);
    }

    #[test]
    fn f8() {
        testing::set_transaction_hash('12345678');
        assert_eq!(get_tx_info().unbox().transaction_hash, '12345678');
    }

    #[test]
    fn f9() {
        testing::set_chain_id('test_chain_id');
        assert_eq!(get_tx_info().unbox().chain_id.into(), 'test_chain_id');
    }

    #[test]
    fn f10() {
        testing::set_nonce('test_nonce');
        assert_eq!(get_tx_info().unbox().nonce, 'test_nonce');
    }

    #[test]
    fn f11() {
        testing::set_signature(array!['r', 's'].span());
        let s = get_tx_info().unbox().signature;
        assert_eq!(*s[0], 'r');
        assert_eq!(*s[1], 's');
    }

    #[test]
    fn f12() {
        testing::set_block_hash(12345678, 'value');
        assert_eq!(get_tx_info().unbox().block_hash, 12345678);
    }

    #[test]
    fn f13() {
        let contract_address = starknet::contract_address_const::<0x42>();
        let _log = testing::pop_log_raw(contract_address);
    }

    #[derive(Drop, starknet::Event)]
    struct TestEvent {
        #[key]
        id: u32,
        data: felt252,
    }

    #[test]
    fn f14() {
        let contract_address = starknet::contract_address_const::<0x42>();
        let _log = testing::pop_log::<TestEvent>(contract_address);
    }

    #[test]
    fn f15() {
        let contract_address = starknet::contract_address_const::<0x42>();
        let _msg = testing::pop_l2_to_l1_message(contract_address);
    }
}
```

2024-07-31 23:41 UTC, glihm commented on docs/pages/framework/testing-cheat-codes.md
> +In conclusion, the Cairo cheat codes provide a powerful toolset for testing and debugging Starknet contracts. By mastering these cheat codes, you can simulate various scenarios, test edge cases, and
```suggestion
In conclusion, the Cairo cheat codes provide a powerful toolset for testing and debugging Starknet contracts. By mastering these cheat codes, you can simulate various scenarios, test edge cases, and ensure the correctness of your contracts. With this guide, you are now well-equipped to tackle dojo testing which heavily uses those cheat codes.
```

2024-08-07 08:08 UTC, od-hunter commented
gm sir
i am a bit stuck in the last 3 there test examples: `pop_log_raw`, `pop_log`, `pop_l2_to_l1_message`

i don’t know how to go about writing the assert statments for them 
please can you assist me with resources to solve it

2024-08-10 21:43 UTC, glihm commented
> gm sir @glihm i am a bit stuck in the last 3 there test examples: `pop_log_raw`, `pop_log`, `pop_l2_to_l1_message`
> 
> i don’t know how to go about writing the assert statments for them please can you assist me with resources to solve it

Sorry for the delay here.

For the messages, you can skip them for now. These are not used that much for the moment in Dojo.

In the meantime, the `pop_log` is very used and important.
To test it correctly, you should have a contract that actually emits an event. And then the event will be caught by this cheat code.

What you can do to make the full test, write a minimal contract that emits an event, call the function that emits the event, and then pop the log.

A minimal contract could look something like this:
```rust
#[starknet::interface]
pub trait IContract<T> {
    fn emit_log(ref self: T);
}

#[starknet::contract]
pub mod MyContract {
    #[abi(embed_v0)]
    impl IContractImpl of IContract<ContractState> {
        fn emit_log(ref self: ContractState) {
            starknet::emit(.....);
        }
    }
}
```
You can use the demo event, don't forget to declare inside the contract. 👍

2024-08-11 20:48 UTC, od-hunter commented
@glihm , please review

2024-08-13 16:15 UTC, glihm approved these changes
Thank you @od-hunter for the work done here!

2024-08-13 16:16 UTC, od-hunter commented
Thank you sir @glihm , I’m open to more issues🚀🚀

2024-08-13 16:19 UTC, merged